services:
  app:
    image: killlluck/restaurante-caio:staging
    container_name: restaurante-caio-app
    ports:
      - "8091:3000"
    environment:
      DB_HOST: dbcentral
      DB_USER: root
      DB_PASS: password
      DB_NAME: marmitadb
    networks:
      - rede_alunos

networks:
  rede_alunos:
    external: true
